Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -35,46 +35,15 @@ jobs:
           distribution: 'adopt'
           architecture: 'x64'
 
-      - name: Run Snyk to check for vulnerabilities (Discovery Service)
-        uses: snyk/actions/maven@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          command: 'test'
-          args: '--all-projects --sarif-file-output=snyk-discovery.sarif'
-          directory: backend-application/discovery-service
-
-      - name: Run Snyk to check for vulnerabilities (Cloud Gateway Service)
-        uses: snyk/actions/maven@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          command: 'test'
-          args: '--all-projects --sarif-file-output=snyk-cloud-gateway.sarif'
-          directory: backend-application/cloud-gateway-service
-
-      - name: Run Snyk to check for vulnerabilities (Favourite Service)
-        uses: snyk/actions/maven@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          command: 'test'
-          args: '--all-projects --sarif-file-output=snyk-favourite.sarif'
-          directory: backend-application/favourite-service
-# ...
-
-      - name: Snyk Code test (Discovery Service)
+      - name: Snyk Code test - Run Snyk to check for vulnerabilities (Discovery Service)
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: |
           cd backend-application/discovery-service
           mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
           snyk code test --all-projects --sarif-file-output=snyk-code-discovery.sarif
-
-# ...
-
-    
-      - name: Snyk Code test (Cloud Gateway Service)
+          
+      - name: Snyk Code test - Run Snyk to check for vulnerabilities (Cloud Gateway Service)
         env:
             SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: |
@@ -82,7 +51,7 @@ jobs:
           mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
           snyk code test --all-projects --sarif-file-output=snyk-code-cloud-gateway.sarif
 
-      - name: Snyk Code test (Favourite Service)
+      - name: Snyk Code test - Run Snyk to check for vulnerabilities (Favourite Service)
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: |
@@ -98,19 +67,19 @@ jobs:
 #         with:
 #           args: --sarif-file-output=snyk.sarif
 
-#         # Run Snyk Code (SAST) analysis and uploads result into GitHub
-#         # Use || true to not fail the pipeline
-#       - name: Snyk Code test
-#         run: |
-#           cd /backend-application/discovery-service
-#           snyk code test --sarif > snyk-code.sarif || true
-#           snyk test --maven-aggregate-project
+        # Run Snyk Code (SAST) analysis and uploads result into GitHub
+        # Use || true to not fail the pipeline
+      - name: Snyk Code test
+        run: |
+          cd /backend-application/discovery-service
+          snyk code test --sarif > snyk-code.sarif || true
+          snyk test --maven-aggregate-project
 
-#         # Run Snyk Open Source (SCA) analysis and uploads result to Snyk
-#       - name: Snyk Open Source monitor
-#         run: snyk monitor --all-projects
-#         env:
-#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        # Run Snyk Open Source (SCA) analysis and uploads result to Snyk
+      - name: Snyk Open Source monitor
+        run: snyk monitor --all-projects
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
         # Build the docker image for testing
 #       - name: Build docker image
