Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -36,52 +36,56 @@ jobs:
           architecture: 'x64'
 
 
-# -------------
-      - name: Snyk Code test - Run Snyk to check for vulnerabilities (Discovery Service)
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        run: |
-          cd backend-application/discovery-service
-          mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
-          snyk code test --all-projects --sarif-file-output=snyk-code-discovery.sarif
-          
-      - name: Snyk Code test - Run Snyk to check for vulnerabilities (Cloud Gateway Service)
-        env:
-            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        run: |
-          cd backend-application/cloud-gateway-service
-          mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
-          snyk code test --all-projects --sarif-file-output=snyk-code-cloud-gateway.sarif
-
-      - name: Snyk Code test - Run Snyk to check for vulnerabilities (Favourite Service)
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        run: |
-          cd backend-application/favourite-service
-          mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
-          snyk code test --all-projects --sarif-file-output=snyk-code-favourite.sarif
-# --------------        
-
-        # Run Snyk Code (SAST) analysis and uploads result into GitHub
-        # Use || true to not fail the pipeline
-#       - name: Snyk Code test
+# # -------------
+#       - name: Snyk Code test - Run Snyk to check for vulnerabilities (Discovery Service)
 #         env:
 #           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 #         run: |
 #           cd backend-application/discovery-service
 #           mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
-#           snyk code test --sarif > snyk-code.sarif || true
-#           snyk test --all-projects --sarif-file-output=snyk-test.sarif
+#           snyk code test --all-projects --sarif-file-output=snyk-code-discovery.sarif
           
-#           cd backend-application/discovery-service
+#       - name: Snyk Code test - Run Snyk to check for vulnerabilities (Cloud Gateway Service)
+#         env:
+#             SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+#         run: |
+#           cd backend-application/cloud-gateway-service
 #           mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
-#           snyk code test --sarif > snyk-code.sarif || true
-#           snyk test --maven-aggregate-project
+#           snyk code test --all-projects --sarif-file-output=snyk-code-cloud-gateway.sarif
+
+#       - name: Snyk Code test - Run Snyk to check for vulnerabilities (Favourite Service)
+#         env:
+#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+#         run: |
+#           cd backend-application/favourite-service
+#           mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
+#           snyk code test --all-projects --sarif-file-output=snyk-code-favourite.sarif
+# # --------------        
+
+        # Run Snyk Code (SAST) analysis and uploads result into GitHub
+        # Use || true to not fail the pipeline
+      - name: Snyk Code test --- long
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        run: |
+          cd backend-application/discovery-service
+          mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
+          snyk code test --sarif > snyk-code.sarif || true
+          snyk test --all-projects --sarif-file-output=snyk-test.sarif
+         
+      - name: Snyk Code test --- maven-aggregate-project
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        run: |
+          cd backend-application/discovery-service
+          mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
+          snyk code test --sarif > snyk-code.sarif || true
+          snyk test --maven-aggregate-project
       
-#       - name: Upload Snyk test results
-#         uses: github/codeql-action/upload-sarif@v1
-#         with:
-#           sarif_file: snyk-test.sarif
+      - name: Upload Snyk test results
+        uses: github/codeql-action/upload-sarif@v1
+        with:
+          sarif_file: snyk-test.sarif
           
           
           
